import PropTypes from "prop-types";

export const SharePopTypes = {
  e: PropTypes.any,
  Idx: PropTypes.string,
  site: PropTypes.string,
  title: PropTypes.string,
  isLargeLength: PropTypes.bool,
};

export const TranslateViewTypes = {
  _changeCodeToEn: PropTypes.func,
  _changeCodeToHi: PropTypes.func,
  isHindiTranslate: PropTypes.bool,
  translateContent: PropTypes.string,
};

export const EmailLinkPropTypes = {
  email: PropTypes.string,
  subject: PropTypes.string,
};

export const ContentPropTypes = {
  selectedKanda: PropTypes.string,
  selectedSarga: PropTypes.number,
  selectedShloka: PropTypes.number,
  shlokaData: PropTypes.object,
  sanEng: PropTypes.func,
  isSharePopVisible: PropTypes.bool,
  clickEvent: PropTypes.object,
  handleClick: PropTypes.func,
  shareRef: PropTypes.object,
  shId: PropTypes.string,
  site: PropTypes.string,
  hideTrans: PropTypes.bool,
  _hideTrans: PropTypes.func,
  handleKandaChange: PropTypes.func,
  handleSargaChange: PropTypes.func,
  handleShlokaChange: PropTypes.func,
  handleSargaLen: PropTypes.func,
  handleShlokaLen: PropTypes.func,
  shareTitle: PropTypes.string,
  _changeCodeToEn: PropTypes.func,
  _changeCodeToHi: PropTypes.func,
  handleChapterChange: PropTypes.func,
  handleSholkaChange: PropTypes.func,
  isHindiTranslate: PropTypes.bool,
  OptionLength: PropTypes.number,
  selectedChapter: PropTypes.number,
  ShlokaContent: PropTypes.string,
  translateContent: PropTypes.string,
};

export const OtherGitasPropTypesv1 = {
  selectedChapter: PropTypes.any,
  handleChapterChange: PropTypes.any,
  selectedShloka: PropTypes.any,
  handleShlokaChange: PropTypes.any,
  OptionLength: PropTypes.any,
  shId: PropTypes.any,
  ShlokaContent: PropTypes.any,
  handleClick: PropTypes.any,
  shareRef: PropTypes.any,
  _hideTrans: PropTypes.any,
  hideTrans: PropTypes.any,
  _changeCodeToEn: PropTypes.any,
  _changeCodeToHi: PropTypes.any,
  isHindiTranslate: PropTypes.any,
  translateContent: PropTypes.any,
  isSharePopVisible: PropTypes.any,
  clickEvent: PropTypes.any,
  site: PropTypes.any,
  shareTitle: PropTypes.any,
};

export const OtherGitasPropTypesv2 = {
  selectedShloka: PropTypes.any,
  handleShlokaChange: PropTypes.any,
  OptionLength: PropTypes.any,
  shId: PropTypes.any,
  ShlokaContent: PropTypes.any,
  handleClick: PropTypes.any,
  shareRef: PropTypes.any,
  _hideTrans: PropTypes.any,
  hideTrans: PropTypes.any,
  _changeCodeToEn: PropTypes.any,
  _changeCodeToHi: PropTypes.any,
  isHindiTranslate: PropTypes.any,
  translateContent: PropTypes.any,
  clickEvent: PropTypes.any,
  site: PropTypes.any,
  shareTitle: PropTypes.any,
  isSharePopVisible: PropTypes.any,
};

export const YogaSutraPropTypes = {
  selectedChapter: PropTypes.any,
  handleChapterChange: PropTypes.any,
  selectedSutra: PropTypes.any,
  handleSutraChange: PropTypes.any,
  OptionLength: PropTypes.any,
  handleCheckboxChange: PropTypes.any,
  isViewBhasya: PropTypes.any,
  isViewSutra: PropTypes.any,
  isViewVritti: PropTypes.any,
  shsId: PropTypes.any,
  SutraContent: PropTypes.any,
  handleClick: PropTypes.any,
  setShareTC: PropTypes.any,
  shareRefB: PropTypes.any,
  shareRefS: PropTypes.any,
  shareRefV: PropTypes.any,
  shareTitle: PropTypes.any,
  shbId: PropTypes.any,
  shvId: PropTypes.any,
  BhasyaContent: PropTypes.any,
  VrittiContent: PropTypes.any,
  _hideTrans: PropTypes.any,
  hideTrans: PropTypes.any,
  _changeCodeToEn: PropTypes.any,
  _changeCodeToHi: PropTypes.any,
  isHindiTranslate: PropTypes.any,
  setWhichSutra: PropTypes.any,
  whichSutra: PropTypes.any,
  translateContent: PropTypes.any,
  clickEvent: PropTypes.any,
  shId: PropTypes.any,
  site: PropTypes.any,
  isSharePopVisible: PropTypes.any,
  areAnyCheckboxesChecked: PropTypes.any,
};
